### ISSUE TITLE
学长你好，我最近在整理一份IT笔试面试的知识库，翻译了这里的一部分内容

### ISSUE THREAD

**Issue by skyline75489** [AustinChou/My-Knowledge-Base#1]
仓库： https://github.com/HIT-Alibaba/interview/wiki

想向学长表示一下感谢，谢谢学长整理出这么好的内容。

我自己只能算是刚入门iOS开发，有些地方可能翻译的不正确，如果学长对上面那个仓库有兴趣的话，也随时欢迎贡献内容。

**Comment by AustinChou** [comment]
@skyline75489 明显的同届的好嘛 XD

**Comment by skyline75489** [comment]
@AustinChou  是吗，你也是大三？

**Comment by AustinChou** [comment]
@skyline75489 是啊，欢迎互相学习，我是计算机学院的。BTW，你的 Wiki 整理也非常棒！
